# Generated by Django 3.2.9 on 2021-12-24 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_auto_20211217_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='bookmarked_users',
            field=models.ManyToManyField(null=True, related_name='bookmarked_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
