# Generated by Django 3.2.9 on 2021-11-21 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20211121_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movies.year'),
        ),
        migrations.AlterField(
            model_name='year',
            name='id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
